#!/bin/bash

# the command below was used to generate the imp files from the
# txt files. regenerate these files, comment it in:
# emacs --batch --load myrio.el
rm -f myrio.zip
mkdir -p release/modules/texts/ztext/myrio
mkdir -p release/mods.d
imp2vs myrio.imp -z -o release/modules/texts/ztext/myrio
rm release/modules/texts/ztext/myrio/ot.*
cp myrio.conf release/mods.d/
cd release
7z a ../myrio.zip .
rm -rf ../release


