#!/bin/bash

emacs --batch --load oikos.el
cat texts/*.imp > oikos.imp
mkdir -p release/modules/texts/ztext/oikos
mkdir -p release/mods.d
imp2vs oikos.imp -z -o release/modules/texts/ztext/oikos
rm release/modules/texts/ztext/oikos/ot.*
cp oikos.conf release/mods.d/
cd release
7z a ../oikos.zip .
rm -rf ../release
rm oikos.imp


